name: CreativeEconomy
main: ifteam\CreativeEconomy\CreativeEconomy
version: 0.5-Alpha
author: ifteam
api: [1.12.0]

permissions:
 creativeeconomy.commands.buy:
  default: true
 creativeeconomy.commands.sell:
  default: true
 creativeeconomy.commands.ce:
  default: OP
 creativeeconomy.shop.use:
  default: true
 creativeeconomy.shop.break:
  default: OP